#!/usr/bin/env bash
# Start the Mac demo stores (Plateau :8080, Sage & Poppy :8082) at login, each with
# its own .demo/<store>/store.env (gitignored; the cloud keys stay there — the
# generated plists only name the store, never a key).
#
#   scripts/demo-autostart.sh install   [--store plateau|sage-poppy|all]   # default all
#   scripts/demo-autostart.sh uninstall [--store …]
#   scripts/demo-autostart.sh status    [--store …]
#   scripts/demo-autostart.sh start|stop|restart [--store …]   # now, with store.env
#
# install writes ~/Library/LaunchAgents/dev.dwhipstock.pos.demo.<store>.plist and
# loads it. A store that is already running is left alone (the agent sees the port
# is taken and exits quietly); from the next login on, launchd starts it.
# No KeepAlive on purpose: stopping a store (demo-down.sh, demo-reset.sh) must not
# make launchd start it again behind your back. Logs: <data dir>/store.log.
#
# .demo/<store>/store.env must exist first — scripts/demo-reset.sh captures it
# from the running store (or write it by hand; see scripts/lib/demo-store.sh).
set -euo pipefail

# shellcheck source=lib/demo-store.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/demo-store.sh"
SELF="$REPO_ROOT/scripts/demo-autostart.sh"

CMD="${1:-}"; shift || true
STORES="plateau sage-poppy"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --store) case "${2:-}" in all) ;; plateau|sage-poppy) STORES="$2";; *) demo_err "--store plateau|sage-poppy|all"; exit 2;; esac; shift 2;;
    *) [[ "$CMD" == run ]] && break; demo_err "unknown option $1"; exit 2;;
  esac
done

xml_escape() { sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }

write_plist() { # store
  local store="$1" plist label log
  plist="$(demo_agent_plist "$store")"; label="$(demo_agent_label "$store")"
  log="$DEMO_DATA_DIR/store.log"
  mkdir -p "$(dirname "$plist")"
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/demo-autostart.sh — the store's settings and keys live in
     $(demo_env_file "$store" | xml_escape), not here. -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$(echo "$SELF" | xml_escape)</string>
    <string>run</string>
    <string>$store</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>POS_DEMO_ROOT</key><string>$(echo "$DEMO_ROOT" | xml_escape)</string>
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>$(echo "$log" | xml_escape)</string>
  <key>StandardErrorPath</key><string>$(echo "$log" | xml_escape)</string>
</dict>
</plist>
PLIST
  plutil -lint "$plist" >/dev/null
}

case "$CMD" in
  install)
    for s in $STORES; do
      demo_load_env "$s"
      [[ -x "$DEMO_JAVA" ]] || { demo_err "$s: java not found at DEMO_JAVA=$DEMO_JAVA"; exit 1; }
      [[ -f "$DEMO_JAR" ]] || { demo_err "$s: jar not found at $DEMO_JAR"; exit 1; }
      write_plist "$s"
      launchctl bootout "gui/$(id -u)/$(demo_agent_label "$s")" 2>/dev/null || true
      launchctl bootstrap "gui/$(id -u)" "$(demo_agent_plist "$s")"
      echo "$s: installed $(demo_agent_plist "$s") (starts at login; cloud: $DEMO_CLOUD)"
    done
    ;;
  uninstall)
    for s in $STORES; do
      was_up=0
      if [[ -f "$(demo_env_file "$s")" ]]; then
        demo_load_env "$s"
        [[ -n "$(demo_port_pid "$POS_PORT")" ]] && was_up=1
      fi
      # unloading stops a store launchd started; bring it back detached so the
      # demo keeps running — only the login-time start goes away
      launchctl bootout "gui/$(id -u)/$(demo_agent_label "$s")" 2>/dev/null || true
      rm -f "$(demo_agent_plist "$s")"
      if [[ "$was_up" == 1 ]]; then
        sleep 2
        [[ -z "$(demo_port_pid "$POS_PORT")" ]] && demo_start_bg "$DEMO_CLOUD" >/dev/null
      fi
      echo "$s: login agent removed$([[ "$was_up" == 1 ]] && echo "; the store is still running on :$POS_PORT")"
    done
    ;;
  status)
    for s in $STORES; do
      if [[ -f "$(demo_env_file "$s")" ]]; then demo_load_env "$s"; else POS_PORT="$(demo_default_port "$s")"; DEMO_DATA_DIR="$DEMO_ROOT/.demo/$s"; DEMO_CLOUD="?"; fi
      pid="$(demo_port_pid "$POS_PORT")"
      printf '%-11s agent: %-13s store: %-24s cloud: %s\n' "$s" \
        "$( [[ -f "$(demo_agent_plist "$s")" ]] && { demo_agent_loaded "$s" && echo installed || echo "not loaded"; } || echo "not installed")" \
        "$( [[ -n "$pid" ]] && { demo_healthy "$POS_PORT" && echo "up :$POS_PORT (pid $pid)" || echo "starting :$POS_PORT"; } || echo "down")" \
        "$DEMO_CLOUD"
    done
    ;;
  start|stop|restart) # right now, same settings as at login (recovery mid-demo)
    for s in $STORES; do
      demo_load_env "$s"
      if [[ "$CMD" != start ]]; then demo_stop; echo "$s: stopped"; fi
      [[ "$CMD" == stop ]] && continue
      if [[ -n "$(demo_port_pid "$POS_PORT")" ]]; then echo "$s: already up on :$POS_PORT"; continue; fi
      if demo_agent_loaded "$s"; then
        launchctl kickstart "gui/$(id -u)/$(demo_agent_label "$s")"
        demo_wait_healthy "$POS_PORT" 60 && echo "$s: up on :$POS_PORT (login agent)" || { demo_err "$s did not come up — tail $DEMO_DATA_DIR/store.log"; exit 1; }
      else
        echo "$s:"; demo_start_bg "$DEMO_CLOUD"
      fi
    done
    ;;
  run) # what launchd runs: exec the store in the foreground with its store.env
    s="${1:-}"
    demo_known_store "$s" || { demo_err "run <plateau|sage-poppy>"; exit 2; }
    demo_load_env "$s"
    if [[ -n "$(demo_port_pid "$POS_PORT")" ]]; then
      echo "$(date '+%H:%M:%S') demo-autostart: :$POS_PORT already in use — $s is running already, nothing to do"
      exit 0
    fi
    echo "$(date '+%H:%M:%S') demo-autostart: starting $s (cloud: $DEMO_CLOUD)"
    demo_exec_fg
    ;;
  *) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 2;;
esac
